telegram connection + basic project structure
nerzon-alcoholics/telegram-bot pull request #1
Opened 2022-11-14 19:58 UTC by pavelitel05

2022-11-15 13:20 UTC, ReDestroyDeR requested changes

2022-11-15 13:20 UTC, ReDestroyDeR commented on pom.xml
> +<!--        </dependency>-->
Удалить

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/java/config/TelegramConfig.java
> +}
Через `@ConfigurationProperties`
https://www.baeldung.com/configuration-properties-in-spring-boot

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/java/handler/CallbackQueryHandler.java
> +        return null;
`throw new UnsupportedOperationException();`

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/java/handler/MessageHandler.java
> +        return null;
`throw new UnsupportedOperationException();`

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/resources/application.properties
> +telegram.webhook-path = https://5f98-178-134-173-28.eu.ngrok.io
в env

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/resources/application.properties
> +telegram.bot-token = ###
в env

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/java/entity/TeleBot.java
> +        return null;
сделай кастомный exception на неотрезолвленное сообщение

2022-11-15 13:20 UTC, ReDestroyDeR commented on src/main/java/entity/TeleBot.java
> +            return null;
Объедини + прокидывай exception

2022-11-15 13:21 UTC, ReDestroyDeR commented on src/main/java/entity/TeleBot.java
> +        return new TelegramConfig().getWebhookPath();
сделай эти свойства полями класса и инициализируй в конструкторе из конфига

2022-11-18 17:13 UTC, ReDestroyDeR requested changes

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/TelegramBotApplication.java
> +        log.info("Hello World!");
Удалить

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/config/TelegramConfig.java
> +}
Билд падает. Нужен @Setter. Проще воткнуть `@Data`
Зачем `@Configuration`?
Зачем `@FieldDefaults`?

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/entity/TeleBot.java
> +        return new TelegramConfig().getWebhook();
Таким образом не получиться получить информацию из кофнига.
Нужна зависимость на `TelegramConfig`,

Как вариант:
```java
@Component
@RequiredArgsConstructor
public class TeleBot extends TelegramWebhookBot {
  private final TelegramConfig cfg;
// ...
```

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/entity/TeleBot.java
> +        return new TelegramConfig().getWebhook();
https://www.baeldung.com/spring-dependency-injection

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/entity/TeleBot.java
>      CallbackQueryHandler callbackQueryHandler;
пометь поля как `private final`

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/exception/UnsupportedOperationException.java
> +}
Такая ошибка есть в java.lang

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/handler/MessageHandler.java
> +        throw new UnsupportedOperationException();
Есть в java.lang

2022-11-18 17:13 UTC, ReDestroyDeR commented on src/main/java/ru/nerzon/alcoholics/telegrambot/exception/UnsupportedOperationException.java
> +}
Даже если определять свой кастомный тип ошибки, нужно делать его unchecked.
checked exception - плохой вкус

2022-11-21 21:16 UTC, pavelitel05 commented on src/main/java/entity/TeleBot.java
> +        return new TelegramConfig().getWebhookPath();
Это абстрактные методы в родителе

2022-11-22 12:22 UTC, ReDestroyDeR approved these changes
нраица

2022-11-22 12:22 UTC, merged